// Native parity gate.
//
// The three data files under ./data are snapshots of what the native compiler
// (build/hmx) produces for every case in the three native suites
// (tests/run_integration.sh, tests/run_negative_tests.sh,
// tests/run_stress_tests.sh). They are generated by
// tools/smoke/gen-data.mts and committed so this suite needs no C toolchain.
//
// Contract (see PLAN.md §2.6):
//  - integration:    47 fixtures + 5 module programs must run with byte-identical
//                    { stdout, stderr, exit }.
//  - stress:         116 output/exit/input cases, byte-identical.
//  - negative:       ~190 compile/runtime error cases: exit != 0, stderr matches
//                    the suite's grep pattern *and* equals the native stderr
//                    verbatim. Module diagnostics are compared entry-relative:
//                    native embeds absolute canonical paths, the web loader uses
//                    the same paths canonicalized relative to the entry (the
//                    generator strips the per-case temp-dir prefix).

import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { runProgram } from "../src/compiler/program";

interface Snapshot {
  stdout: string;
  stderr: string;
  exit: number;
}

interface Case {
  name: string;
  kind:
    | "output"
    | "exit"
    | "input_output"
    | "module_output"
    | "module_exit"
    | "fixture"
    | "module"
    | "negative"
    | "module_negative";
  source: string | null;
  stdin: string | null;
  entry: string | null;
  modules: Record<string, string> | null;
  pattern: string | null;
  expected: Snapshot;
}

function loadCases(file: string): Case[] {
  const raw = readFileSync(new URL(`./data/${file}`, import.meta.url), "utf8");
  return (JSON.parse(raw) as { cases: Case[] }).cases;
}

function run(c: Case): Snapshot {
  if (c.modules && c.entry) {
    const source = c.modules[c.entry];
    expect(source, `${c.name}: entry ${c.entry} present in modules`).toBeDefined();
    return runProgram(source, { modules: c.modules, entryPath: c.entry });
  }
  return runProgram(c.source!, { stdin: c.stdin ?? [] });
}

function describeSuite(file: string, label: string) {
  const cases = loadCases(file);
  describe(label, () => {
    it(`covers ${cases.length} cases`, () => {
      expect(cases.length).toBeGreaterThan(0);
    });
    for (const c of cases) {
      it(c.kind === "negative" || c.kind === "module_negative" ? `fails: ${c.name}` : c.name, () => {
        const r = run(c);

        if (c.kind === "negative" || c.kind === "module_negative") {
          expect(r.exit).not.toBe(0);
          if (c.pattern) {
            expect(r.stderr).toMatch(new RegExp(c.pattern, "i"));
          }
        }

        // Verbatim parity with the native snapshot.
        expect(r.stdout, `${c.name} stdout`).toBe(c.expected.stdout);
        expect(r.stderr, `${c.name} stderr`).toBe(c.expected.stderr);
        expect(r.exit, `${c.name} exit`).toBe(c.expected.exit);
      });
    }
  });
}

describeSuite("integration.json", "integration (fixtures + modules)");
describeSuite("stress.json", "stress & output behavior");
describeSuite("negative.json", "negative / error handling");